import Header from '@/components/header/header'
import getSession from '@/lib/iron'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
// import localFont from 'next/font/local'
import './globals.css'

// const lora = Lora({
//   weight: '400',
//   subsets: ['latin'],
//   variable: '--font-lora',
// })

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-roboto',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await getSession()
  // console.log('session.user: ', session.user)
  return (
    <html lang="en">
      <body className={`${roboto.variable} font-sans antialiased`}>
        <div className="container mx-auto px-4">
          <Header user={session.user} />
          {/* <div className="grid grid-rows-[20px_1fr_20px] items-center justify-items-center min-h-screen p-8 pb-20 gap-16 sm:p-20 font-(family-name:--font-geist-sans)"> */}
          <main className="max-w-xl mx-auto mt-8">{children}</main>
        </div>
      </body>
    </html>
  )
}
